runtime: java11
env: standard
instance_class: F4
inbound_services:
- warmup
handlers:
  - url: .*
    script: auto
  - url: .*
    script: auto
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}